### ISSUE TITLE
Emojis in messages

### ISSUE THREAD

**Issue by maxvanceffer** [alekseysidorov/vreen#35]
Hi i am trying to send emojis inside message, but VK shows  them as usual text. In docs i found only this: http://vk.com/dev/emoji

Can you provide some advice how i can send emoji inside message ?

**Comment by gorthauer** [comment]
I do not treat the contents of text messages and I use utf8 for text encoding. I think you should use rich  text component to render messages. 

For example you can search for special characters and replace them with images.

**Comment by maxvanceffer** [comment]
so, i don't need any additional manipulation from vreen side, to be able send emojis, and vk will interpreted them right ?

**Comment by gorthauer** [comment]
That if the internal json parser does not contains errors. Vreen uses third party parser k8json. If it contains errors with utf8 you can replace it by QJsonDocument.

see 

https://github.com/euroelessar/k8json

and usage

https://github.com/gorthauer/vreen/blob/master/src/api/json.cpp

**Comment by gorthauer** [comment]
I have replaced k8json on QJsonDocument. Can you check the emojis are working now?

**Comment by maxvanceffer** [comment]
Yes. Very good !!!
