### ISSUE TITLE
cannot build with qbs

### ISSUE THREAD

**Issue by luntik2012** [alekseysidorov/vreen#39]
```
qbs install --clean-install-root --install-root $LOCAL_PREFIX release
No build graph exists yet for this configuration.
Resolving project for configuration gcc-debug
ERROR: /home/user/vreen/src/api.qbs:32:5 Product dependency 'Qt.core' not found.
```

**Comment by alekseysidorov** [comment]
did you launch qbs-setup-qt and qbs-setup-toolchains before compilation?

**Comment by luntik2012** [comment]
yes, but now I get "...oauth.qbs:36:9" Dependency 'Qt.webkitwidgets' not found for product 'vreenplugin'"

**Comment by alekseysidorov** [comment]
What is the Qt version did you use?

**Comment by alekseysidorov** [comment]
Also you can look travis and appveyor build scripts.

**Comment by luntik2012** [comment]
there is no build scripts, just some *.yml files. how to run them? google says some garbage on this.
i've used qt 5.7 in the latest comment, but i've the same result on qt 5.5.1

**Comment by alekseysidorov** [comment]
You can see build steps in .yml files. Their syntax is trivial.
```yaml
- brew update
- brew install qt5
- brew link --force qt5
- brew install qbs
- export QBS_SETTINGS_DIR=$HOME/config
- qbs-setup-toolchains --detect
- qbs-setup-qt /usr/local/opt/qt5/bin/qmake qt5
- qbs-config profiles.qt5.baseProfile $CC
- qbs-config defaultProfile qt5
- qbs install project.with_webkit:false
```

**Comment by luntik2012** [comment]
- export QBS_SETTINGS_DIR=$HOME/config
- qbs-setup-toolchains --detect
- qbs-setup-qt /usr/local/opt/qt5/bin/qmake qt5
- qbs-config profiles.qt5.baseProfile $CC
- qbs-config defaultProfile qt5
- qbs install project.with_webkit:false

$ qbs install project.with_webkit:false
No build graph exists yet for this configuration.
Resolving project for configuration qt5-debug
ERROR: /tmp/vreen/src/auth/widget/oauth.qbs:34:9 Product dependency 'Qt.webengine' not found.

**Comment by alekseysidorov** [comment]
It seems that you did not install QtWebEnging

**Comment by luntik2012** [comment]
Yes, it seems Ubuntu 16.04 doesn't have qtwebengine in repos.
That worked using qt installer from website
